<!ELEMENT student-records (student+)>

<!ELEMENT student (name-info, student-contact, academic-history)>

<!ATTLIST student
    id CDATA #REQUIRED>

<!ELEMENT name-info (
  first-name,
  middle-name,
  last-name,
  preferred-name
)>

<!ELEMENT student-contact (email, phone)>

<!ELEMENT academic-history (
  undergrad-year,
  gpa,
  major,
  minor,
  enrollment-status,
  advisor,
  enrollment-date,
  graduation-date
)>

<!ELEMENT first-name (#PCDATA)>
<!ELEMENT middle-name (#PCDATA)>
<!ELEMENT last-name (#PCDATA)>
<!ELEMENT preferred-name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT undergrad-year (#PCDATA)>
<!ELEMENT gpa (#PCDATA)>
<!ELEMENT major (#PCDATA)>
<!ELEMENT minor (#PCDATA)>
<!ELEMENT enrollment-status (#PCDATA)>
<!ELEMENT advisor (#PCDATA)>
<!ELEMENT enrollment-date (#PCDATA)>
<!ELEMENT graduation-date (#PCDATA)>
